FROM mysql:5.7

# More details about the environment variables that can be passed to mysql
# are available on the dockerhub https://hub.docker.com/_/mysql/
ENV MYSQL_ROOT_PASSWORD=root
# database to be created on image startup
ENV MYSQL_DATABASE=zeeguu_test
# user specified here will be granted superuser access on the above db
# see: https://hub.docker.com/_/mysql/
ENV MYSQL_USER=zeeguu_test
ENV MYSQL_PASSWORD=zeeguu_test
